<?xml version="1.0"?>
<robot name="solar_panel" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="config_file" default="$(find solar_panel_sim)/config/solar_panel_config.yaml" />
  <xacro:property name="yaml_file" value="$(arg config_file)" />
  <xacro:property name="config" value="${xacro.load_yaml(yaml_file)}" />

  <xacro:property name="width" value="${config['/**']['ros__parameters']['panel']['width']}" />
  <xacro:property name="base_height" value="${config['/**']['ros__parameters']['panel']['base_height']}" />
  <xacro:property name="column_height" value="${config['/**']['ros__parameters']['panel']['column_height']}" />
  <xacro:property name="depth" value="${config['/**']['ros__parameters']['panel']['depth']}" />
  <xacro:property name="mass" value="${config['/**']['ros__parameters']['panel']['mass']}" />
  <xacro:property name="panel_thickness" value="0.05" />

  <link name="world"/>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${width} ${depth} ${base_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${width} ${depth} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${mass * 0.4}"/>
      <inertia ixx="${(mass * 0.4) / 12.0 * (depth*depth + base_height*base_height)}" ixy="0.0" ixz="0.0"
               iyy="${(mass * 0.4) / 12.0 * (width*width + base_height*base_height)}" iyz="0.0"
               izz="${(mass * 0.4) / 12.0 * (width*width + depth*depth)}"/>
    </inertial>
  </link>

  <joint name="base_to_column" type="fixed">
    <parent link="base_link"/>
    <child link="column_link"/>
    <origin xyz="0 0 ${base_height/2 + column_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="column_link">
    <visual>
      <geometry>
        <cylinder length="${column_height}" radius="${width/8}"/>
      </geometry>
      <material name="red">
        <color rgba="0.8 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${column_height}" radius="${width/8}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${mass * 0.2}"/>
      <inertia ixx="${(mass * 0.2) * (3*(width/8)*(width/8) + column_height*column_height)/12}" ixy="0" ixz="0"
               iyy="${(mass * 0.2) * (3*(width/8)*(width/8) + column_height*column_height)/12}" iyz="0"
               izz="${(mass * 0.2) * (width/8)*(width/8)/2}"/>
    </inertial>
  </link>

  <joint name="azimuth_joint" type="revolute">
    <parent link="column_link"/>
    <child link="azimuth_link"/>
    <origin xyz="0 0 ${column_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${config['/**']['ros__parameters']['joints']['azimuth']['lower']}"
           upper="${config['/**']['ros__parameters']['joints']['azimuth']['upper']}"
           effort="${config['/**']['ros__parameters']['joints']['azimuth']['effort']}"
           velocity="${config['/**']['ros__parameters']['joints']['azimuth']['velocity']}"/>
  </joint>

  <link name="azimuth_link">
    <inertial>
      <mass value="0.5"/>  <!-- Aumentado de 0.1 -->
      <inertia ixx="0.05" ixy="0" ixz="0" iyy="0.05" iyz="0" izz="0.05"/>  <!-- Aumentado de 0.01 -->
    </inertial>
  </link>

  <joint name="elevation_joint" type="revolute">
    <parent link="azimuth_link"/>
    <child link="panel_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${config['/**']['ros__parameters']['joints']['elevation']['lower']}"
           upper="${config['/**']['ros__parameters']['joints']['elevation']['upper']}"
           effort="${config['/**']['ros__parameters']['joints']['elevation']['effort']}"
           velocity="${config['/**']['ros__parameters']['joints']['elevation']['velocity']}"/>
  </joint>

  <link name="panel_link">
    <visual>
      <geometry>
        <box size="${width} ${depth} ${panel_thickness}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${width} ${depth} ${panel_thickness}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${mass * 0.6}"/>  <!-- Aumentado de 0.4 -->
      <inertia ixx="${(mass * 0.6) / 12.0 * (depth*depth + panel_thickness*panel_thickness)}" ixy="0.0" ixz="0.0"
              iyy="${(mass * 0.6) / 12.0 * (width*width + panel_thickness*panel_thickness)}" iyz="0.0"
              izz="${(mass * 0.6) / 12.0 * (width*width + depth*depth)}"/>
    </inertial>
  </link>

  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <update_rate>${config['/**']['ros__parameters']['gazebo']['update_rate']}</update_rate>
      <joint_name>azimuth_joint</joint_name>
      <joint_name>elevation_joint</joint_name>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/solar_panel</robotNamespace>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

</robot>